export const petList = [
  {
    id: 1,
    name: "Elliot",
    type: "Cat",
    appointment: "12/01/2023",
    lastAppointment: "10/01/2023",
    note: "Brush your long-haired cat weekly to prevent matting.",
    vaccine: [
      { id: 1, date: "01/01/22", type: "Rabbies" },
      { id: 2, date: "01/01/22", type: "Feline Viral Rhinotracheitis (FVRCP)" },
      { id: 3, date: "01/01/22", type: "Panleukopenia (FPV)"},
      { id: 4, date: "01/01/22", type: "Feline Calicivirus (FCV)" },
    ],
  },
  {
    id: 2,
    name: "Mitchy",
    type: "Cat",
    appointment: "12/01/2023",
    lastAppointment: "10/01/2023",
    note: "Feed 1 cup of high-quality dry kibble twice daily.",
    vaccine: [
      { id: 1, date: "01/01/22", type: "Rabbies" },
      { id: 2, date: "01/01/22", type: "Feline Viral Rhinotracheitis (FVRCP)" },
      { id: 3, date: "01/01/22", type: "Panleukopenia (FPV)"},
      { id: 4, date: "01/01/22", type: "Feline Calicivirus (FCV)" },
    ],
  },
  {
    id: 3,
    name: "Henry",
    type: "Cat",
    appointment: "12/01/2023",
    lastAppointment: "10/01/2023",
    note: "Follow-up appointments every 3 months for monitoring.",
    vaccine: [
      { id: 1, date: "01/01/22", type: "Rabbies" },
      { id: 2, date: "01/01/22", type: "Feline Viral Rhinotracheitis (FVRCP)" },
      { id: 3, date: "01/01/22", type: "Panleukopenia (FPV)"},
      { id: 4, date: "01/01/22", type: "Feline Calicivirus (FCV)" },
    ],
  },
  {
    id: 4,
    name: "Reggie",
    type: "Dog",
    appointment: "12/01/2023",
    lastAppointment: "10/01/2023",
    note: "This dog exhibits signs of separation anxiety.",
    vaccine: [
      { id:1 ,date: "01/01/22", type: "Rabbies"},
      { id:2 ,date: "01/01/22", type: "Feline Viral Rhinotracheitis (FVRCP)"},
      { id:3 ,date: "01/01/22", type: "Panleukopenia (FPV)"},
      { id:4 ,date: "01/01/22", type: "Feline Calicivirus (FCV)"},
    ],
  },
];
